import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, Show } from "@clerk/nextjs";
import TanStackQueryProvider from "@/shared/providers/tan-stack-query.provider";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased  `}>
        <ClerkProvider>
          <Show when="signed-in">
            <Navbar />
          </Show>
          <TanStackQueryProvider>
            <main className="w-full" style={{ height: "calc(100vh - 64px)" }}>
              {children}
            </main>
          </TanStackQueryProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
